name: Test

on: [push]

jobs:
  test_nginx:
    name: "Check if latest nginx image exists"
    runs-on: ubuntu-latest
    steps:
      - uses: brose-ebike/docker-image-exists-action@main
        id: "nginx"
        name: "Check if nginx exists"
        with:
          image: "nginx"
      - name: "Evalulate result"
        run: |
          echo "${{ steps.nginx.outputs.exists }}"
